lead_gen_dtype= {
    'Priority': 'uint8',
    'Tape Date': 'category',
    'Run Date': 'category',
    'Unnamed: 3': 'float32',
    'Deal ID': 'object',
    'Pros ID': 'object',
    'Servicer Loan ID': 'category',
    'Loan Name': 'object',
    'Address': 'object',
    'City': 'category',
    'State': 'category',
    'Zip': 'category',
    'MSA': 'category',
    'Region': 'category',
    'Orig. Loan Balance': 'category',
    'Cut-off Loan Balance': 'object',
    'Current Loan Balance': 'object',
    'P&I Advances': 'category',
    'T&I Advances': 'category',
    'Other Advances Paid': 'category',
    'Cumulative ASER': 'category',
    'Accrued Unpaid Adv Int': 'category',
    'Total Loan Exposure': 'object',
    'Unnamed: 23': 'float32',
    'Property Type': 'category',
    'Property Sub-Type': 'category',
    '# of Props': 'uint16',
    'Gross Coupon': 'float32',
    'Net Coupon': 'float32',
    'Unnamed: 29': 'float32',
    'Rate Type': 'category',
    'Orig. Terms to Maturity (months)': 'uint16',
    'Current Terms to Maturity (months)': 'uint16',
    'Orig. Amort Terms': 'uint16',
    'Current Amort Terms': 'int64',
    'Orig. IO Terms': 'float32',
    'Current IO Terms': 'float32',
    'Seasoning': 'uint16',
    'Origination Date': 'object',
    'Unnamed: 39': 'float32',
    'Securitization Year': 'uint16',
    'Maturity Date / ARD': 'object',
    'Unnamed: 42': 'float32',
    'Prin. Pmt.': 'category',
    'Int. Pmt.': 'category',
    'Unnamed: 45': 'float32',
    'Modification Desc.': 'category',
    'Modification Date': 'object',
    'Unnamed: 48': 'float32',
    'Originator': 'category',
    'Master Servicer': 'category',
    'Special Servicer': 'category',
    'Trustee': 'category',
    'Borrower Name': 'category',
    'Borrower Address': 'category',
    'Borrower City': 'category',
    'Borrower State': 'category',
    'Borrower Zip': 'category',
    'Borrower Contact': 'category',
    'Borrower Phone #': 'category',
    'County Website': 'category',
    'Unnamed: 61': 'float32',
    'Appraised Value': 'object',
    'Unnamed: 63': 'float32',
    'Appraised Date': 'object',
    'Sq. Ft.': 'float32',
    'Units': 'float32',
    'Unnamed: 67': 'float32',
    'Year Built': 'float32',
    'Year Renovated': 'float32',
    'Financial Stmt. Date': 'object',
    'Revenue Amt.': 'object',
    'Expense Amt.': 'object',
    'NOI': 'float32',
    'NCF': 'float32',
    'Debt Yield': 'category',
    'DSCR': 'float32',
    'Occupancy Rate (%)': 'float32',
    'Current LTV': 'float32',
    'Original LTV': 'float32',
    'Unnamed: 80': 'float32',
    'Lockout': 'uint8',
    'Defeasance': 'uint8',
    'Yield Maint.': 'uint16',
    'Prepay Prem': 'uint16',
    'Open': 'int64',
    'Unnamed: 86': 'float32',
    'Current Call Protection Status': 'category',
    'Defeasance Cost': 'float32',
    'Prepay Prem Amt.': 'object',
    'Prepay Prem % of UPB': 'float32',
    'Mstar Cap Rate': 'float32',
    'Cap Rate Used for Prop Value': 'float32',
    'Estimated Property Value': 'object',
    'Estimated LTV': 'float32',
    'Payoff Amount': 'float32',
    'Refinancing Proceeds': 'object',
    'Refinancing Proceeds % of UPB': 'object',
    'Unnamed: 98': 'float32',
    'Loan Status': 'category',
    'Special Serviced Ind': 'category',
    'MR SS Xfer Date': 'object',
    'Unnamed: 102': 'float32',
    'Watchlist Ind': 'category',
    'Servicer Watchlist Date': 'object',
    'WL Codes': 'category',
    'Bankruptcy Ind': 'category',
    'B-Piece Buyer': 'category',
    'Links': 'float32'
    }
