datax_prop_dtype = {
    'Deal ID': 'object',
    'Pros ID': 'object',
    'Property Number': 'category',
    'Tape Date': 'category',
    'Servicer Loan ID': 'object',
    'Servicer Prospectus Loan ID': 'object',
    'Property Name': 'object',
    'Property Address': 'object',
    'Property Square Feet': 'float32',
    'Date Lease Rollover Review': 'category',
    'Percent Expiring 1-12 months': 'float32',
    'Percent Expiring 13-24 months': 'float32',
    'Percent Expiring 25-36 months': 'float32',
    'Percent Expiring 37-48 months': 'float32',
    'Largest Tenant Name': 'object',
    'Largest Tenant Square Feet': 'float32',
    'Largest Tenant Lease Expiration': 'object',
    'Second Largest Tenant Name': 'object',
    'Second Largest Tenant Square Feet': 'float32',
    'Second Largest Tenant Lease Expiration': 'object',
    'Third Largest Tenant Name': 'object',
    'Third Largest Tenant Square Feet': 'float32',
    'Third Largest Tenant Lease Expiration': 'object',
    'Fourth Largest Tenant Name': 'object',
    'Fourth Largest Tenant Square Feet': 'float32',
    'Fourth Largest Tenant Lease Expiration': 'object',
    'Fifth Largest Tenant Name': 'object',
    'Fifth Largest Tenant Square Feet': 'float32',
    'Fifth Largest Tenant Lease Expiration': 'object',
    'Property Type': 'category',
    'Current Balance': 'float32',
    'State': 'category',
    'Year Built': 'float32',
    'Year Renovated': 'float32',
    'ZIP': 'category',
    'City': 'category',
    'Ground Lease Indicator': 'float32',
    'Credit Tenant Lease': 'category'
    }
