datax_loan_dtype = {
    'Deal ID': 'object',
    'Pros ID': 'object',
    'Tape Date': 'category',
    'Servicer Loan ID': 'object',
    'Servicer Prospectus Loan ID': 'object',
    'Asset Name': 'object',
    'City': 'category',
    'State': 'category',
    'ZIP': 'category',
    'Current Balance Amount': 'float32',
    'Maturity Date': 'category',
    'Maturity Months': 'float32',
    'Asset Type': 'category',
    'Property Subtype': 'category',
    'Most Recent Start Date': 'category',
    'Most Recent End Date': 'object',
    'Most Recent Number of Months': 'float32',
    'Most Recent Revenue': 'float32',
    'Most Recent Expense': 'float32',
    'Most Recent NOI': 'float32',
    'Most Recent NCF': 'float32',
    'Most Recent NOI DSCR': 'float32',
    'Most Recent NCF DSCR': 'float32',
    'Most Recent Occupancy Rate': 'float32',
    'Most Recent Appraisal Date': 'object',
    'Most Recent Appraised Value': 'float32',
    'Most Recent Assumption Date': 'object',
    'Most Recent Modification': 'category',
    'Most Recent Modification Date': 'object',
    'Modified Payment Rate': 'float32',
    'Modified Rate': 'float32',
    'Special Serviced Indicator': 'category',
    'Special Servicer': 'category',
    'Amortization Type': 'category',
    'Hyper Amortization Date': 'category',
    'I/O End Date': 'category',
    'Workout Code': 'category',
    'Workout Fee Amount': 'float32',
    'Date Added To Watchlist': 'object',
    'Resolution Date': 'category',
    'Foreclosure Date': 'category',
    'REO Date': 'category',
    'Call Protection Summary': 'category',
    'Loan Paid To Date': 'object',
    'Loan Status Type': 'category',
    'Paid Off Date': 'object',
    'Appraisal Reduction Amount': 'float32',
    'Appraisal Reduction Date': 'category',
    'Liquidation Code': 'category',
    'Liquidation Expense': 'float32',
    'Liquidation Fee Amount': 'float32',
    'Net Proceeds Received  on Liquidation ': 'float32',
    'Realized Loss': 'float32',
    'Servicer Transation ID': 'category',
    'Balloon Indicator': 'category',
    'Bloomberg Deal ID': 'category',
    'Crossed Loan ID': 'category',
    'Cumulative ASER': 'float32',
    'Most Recent ASER': 'float32',
    'Defeasance': 'float32',
    'Defeasance Status': 'category',
    'Prepayment Penalty': 'float32',
    'Prepayment Penalty Amount': 'float32',
    'Cumulative Accrued Unpaid Advance Interest': 'float32',
    'Other Advances': 'float32',
    'Other Principal Adjustments': 'float32',
    'P&I Advances': 'float32',
    'Reimbursed Interest On Advances': 'float32',
    'Special Servicing Fee Amount Plus Adjustments': 'float32',
    'T&I Advances': 'float32',
    'Previous Year Start Date': 'float32',
    'Previous Year End Date': 'object',
    'Previous Year Number of Months': 'float32',
    'Previous Year Revenue': 'float32',
    'Previous Year Expense': 'float32',
    'Previous Year NOI': 'float32',
    'Previous Year NCF': 'float32',
    'Previous Year NOI DSCR': 'float32',
    'Previous Year NCF DSCR': 'float32',
    'Previous Year Occupancy Rate': 'float32',
    'Second Previous Year Start Date': 'float32',
    'Second Previous Year End Date': 'object',
    'Second Previous Year Number of Months': 'float32',
    'Second Previous Year Revenue': 'float32',
    'Second Previous Year Expense': 'float32',
    'Second Previous Year NOI': 'float32',
    'Second Previous Year NCF': 'float32',
    'Second Previous Year NOI DSCR': 'float32',
    'Second Previous Year NCF DSCR': 'float32',
    'Second Previous Year Occupancy Rate': 'float32',
    'Issuance Start Date': 'float32',
    'Issuance End Date': 'object',
    'Issuance Number of Months': 'float32',
    'Issuance Revenue': 'float32',
    'Issuance Expense': 'float32',
    'Issuance NOI': 'float32',
    'Issuance NCF': 'float32',
    'Issuance NOI DSCR': 'float32',
    'Issuance NCF DSCR': 'float32',
    'Issuance Occupancy Rate': 'float32',
    'Yield Maintenance': 'float32',
    'Underwriter': 'category',
    'Underwritten DSCR': 'float32',
    'Underwritten NOI': 'float32',
    'Number Of Properties': 'uint16',
    'Most Recent Debt Service': 'float32',
    'Most Recent Return Date': 'category',
    'Most Recent Transfer Date': 'object',
    'MSA': 'category',
    'Loan Origination Date': 'object',
    'Property Square Feet': 'float32',
    'Current Balance per Square Foot': 'float32',
    'Bankruptcy Date': 'category',
    'Bankruptcy Indicator': 'category',
    'Number Of Installments Paid': 'float32',
    'Number Of Remaining Installments': 'int64',
    'Deal Type': 'category',
    'Original Loan Amount': 'float32',
    'Original LTV': 'float32',
    'Master Servicer ': 'category',
    'NOI': 'float32',
    'Occupancy Rate': 'float32',
    'Original Amortization Term Months': 'uint16',
    'Original Interest Only Term': 'float32',
    'Debt Yield': 'float32',
    'DSCR': 'float32',
    'DSCR At Cutoff': 'float32',
    'Loan Originator': 'category',
    'Remaining Interest Only Term': 'float32',
    'Units': 'float32',
    'Coupon': 'float32',
    'Borrower Name': 'category',
    'Trepp Loan ID': 'category',
    'Securitized LTV': 'float32',
    'Factor': 'float32',
    'Total Number Of Installments': 'uint16'
    }
